### ISSUE TITLE
Testing and Travis CI

### ISSUE THREAD

**Issue by idmontie** [gios-asu/newsletter-wp-plugin#3]
Need Unit Tests and Continuous Integration tools.

**Comment by idmontie** [comment]
Emailed the Comms team so that we can get real input data, real output data and create an integration test from that.

The integration test will be very helpful going into the future once we make a new Board Letter.

**Comment by rraub** [comment]
@idmontie did you ever get anything back from the Comms team?

**Comment by idmontie** [comment]
No, but it seems like they like the results, so it's safe to say the current output is as expected.

**Comment by rraub** [comment]
phpunit test framework is now running thanks to PR #14
